[user]
name = "Cameron Wong"
email = "cam@camdar.io"

[ui]
conflict-marker-style = "git"

[signing]
behavior = "drop"
backend = "gpg"

[git]
sign-on-push = true

[revset-aliases]
'closest_bookmark(to)' = 'heads(::to & bookmarks())'
'closest_pushable(to)' = 'heads(::to & ~description(exact:"") & (~empty() | merges()))'
'slice()' = 'slice(@)'
'slice(from)' = 'ancestors(reachable(from, mutable()), 2)'
"immutable_heads()" = "builtin_immutable_heads() | (trunk().. & ~mine())"

[aliases]
tug = ["bookmark", "move", "--from", "closest_bookmark(@)", "--to", "closest_pushable(@)"]
tug- = ["bookmark", "move", "--from", "closest_bookmark(@-)", "--to", "@-"]
long = ["log", "-T", "builtin_log_detailed"]
slice = ["log", "-r", "slice()"]
sync = ['git', 'fetch', '--all-remotes']
fetch = ['git', 'fetch']
pull = ['util', 'exec', '--', 'sh', '-c', 'jj git fetch && jj new "closest_bookmark(@)"']
push = ['git', 'push']
