" Allow multiple buffers in the same window
set hidden
" Better command-line completion
set wildmenu

set splitbelow

let g:airline_powerline_fonts = 1

let maplocalleader = ",,"

" Ensure that we are in modern vim mode, not backwards-compatible vi mode
set nocompatible
set backspace=indent,eol,start
if has("nvim")
  set guicursor=i:ver25-iCursor
endif

set clipboard=unnamedplus

if has("nvim")
  let g:python3_host_prog = '/home/cam/neovim3/bin/python'
endif

set nofoldenable
let g:vim_markdown_folding_disabled = 1

let g:vim_markdown_math = 1
let g:vim_markdown_frontmatter = 1

set hidden

let g:cornelis_agda_prefix = "\\"

let g:ranger_replace_netrw = 1

let g:current_line_whitespace_disabled_soft = 1

"let g:tex_fast = ""
let g:vimtex_syntax_enabled = 0
let g:vimtex_mappings_enabled = 0
let g:vimtex_syntax_conceal = {}
let g:vimtex_fold_enabled = 0
"let g:vimtex_enabled = 0
"
let data_dir = has('nvim') ? stdpath('data') . '/site' : '~/.vim'
if empty(glob(data_dir . '/autoload/plug.vim'))
  silent execute '!curl -fLo '.data_dir.'/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin()

Plug 'ntpeters/vim-better-whitespace'

Plug 'neovimhaskell/haskell-vim'
Plug 'itchyny/vim-haskell-indent'

Plug 'godlygeek/tabular'
Plug 'preservim/vim-markdown'

if has("nvim")
  Plug 'rbgrouleff/bclose.vim'
endif
Plug 'francoiscabrol/ranger.vim'

Plug 'Asheq/close-buffers.vim'

Plug 'nvim-lualine/lualine.nvim'
Plug 'nvim-tree/nvim-web-devicons'
Plug 'akinsho/bufferline.nvim'

Plug 'christophermca/meta5'
Plug 'flazz/vim-colorschemes'

Plug 'tpope/vim-obsession'

Plug 'CharlesGueunet/VimFilify'

if has("nvim")
  Plug 'sbdchd/neoformat'
else
  Plug 'Chiel92/vim-autoformat'
endif

Plug 'psf/black'

Plug 'junegunn/fzf.vim'

Plug 'ocaml/vim-ocaml'

Plug 'tpope/vim-abolish'

if has("nvim")
  Plug 'neovim/nvim-lspconfig'
  Plug 'mason-org/mason.nvim'
  Plug 'mason-org/mason-lspconfig.nvim'

  Plug 'lifepillar/vim-mucomplete'

  Plug 'kana/vim-textobj-user'
  Plug 'neovimhaskell/nvim-hs.vim'
  Plug 'liuchengxu/vim-which-key'
  Plug 'isovector/cornelis', { 'do': 'stack build' }

  Plug 'nvim-lua/plenary.nvim'
  Plug 'scalameta/nvim-metals'

  Plug 'lervag/vimtex'

  Plug 'MunifTanjim/nui.nvim'
  Plug 'ShinKage/idris2-nvim'

  Plug 'whonore/Coqtail'
  Plug 'NLKNguyen/papercolor-theme'

  Plug 'kaarmu/typst.vim'
  Plug 'nvim-treesitter/nvim-treesitter', {'do': ':TSUpdate', 'branch': 'main'}

  Plug 'Julian/lean.nvim'
endif

Plug 'dpc/vim-armasm'
Plug 'CT075/gbafe-event.vim'
Plug 'will133/vim-dirdiff'

call plug#end()

syntax on
filetype on
filetype indent on
filetype plugin on

let g:airline#extensions#tabline#enabled = 1

set ruler
set number

set tabstop=2
set shiftwidth=2
set expandtab

hi clear SignColumn

augroup CoqtailHighlights
  autocmd!
  autocmd ColorScheme * hi def CoqtailChecked ctermbg=darkblue guibg=darkblue
  autocmd ColorScheme * hi def CoqtailSent    ctermbg=blue guibg=blue
augroup END

if exists('+termguicolors')
  "let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
  "let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
  set termguicolors
  colorscheme molokai
endif

set smartindent
set showcmd
set colorcolumn=80

" Quickly time out on keycodes, but never time out on mappings
set notimeout ttimeout ttimeoutlen=10

let g:bufferline_rotate=1

let mapleader=","

map <C-Right> :bnext<CR>
map <C-Left> :bprevious<CR>
map <C-k> :bnext<CR>
map <C-j> :bprevious<CR>
map <leader>d :Bdelete this<CR>

map <C-P> :Files<CR>

map <C-O> :RangerCurrentDirectory<CR>
nmap <Space> :

nnoremap gV `[v`]

let asmsyntax='armasm'
let filetype_inc='armasm'

nnoremap <F2> :GundoToggle<CR>

nnoremap <leader>m :make<CR>
nnoremap <C-Up> :cn<CR>
nnoremap <C-Down> :cp<CR>

set incsearch
set hlsearch

nnoremap <leader>w :w<CR>

nnoremap <Tab> >>
nnoremap <S-Tab> <<

nnoremap <F2> :UndotreeToggle<cr>

let g:haskell_indent_disable=1

" don't clutter with swap files while using gvim
if has("gui_running")
  set noswapfile
  set nobackup
  set nowritebackup
endif

" Enable statusbar
set laststatus=2

set mouse=a

let g:airline_theme='luna'
let g:bufferline_echo=0

" this doesn't actually work either
if &filetype ==# 'ocaml'
" aaaaaaaaaaaaaaa ftplugin isn't working so we have to do this every time
" if neovim stalls on open it's because opam is being terrible

  " ## added by OPAM user-setup for vim / base ## 93ee63e278bdfc07d1139a748ed3fff2 ## you can edit, but keep this line
  let s:opam_share_dir = system("opam var share")
  let s:opam_share_dir = substitute(s:opam_share_dir, '[\r\n]*$', '', '')

  let s:opam_configuration = {}

  function! OpamConfOcpIndent()
    "execute "set rtp^=" . s:opam_share_dir . "/ocp-indent/vim"
  endfunction
  let s:opam_configuration['ocp-indent'] = function('OpamConfOcpIndent')

  function! OpamConfOcpIndex()
    execute "set rtp+=" . s:opam_share_dir . "/ocp-index/vim"
  endfunction
  let s:opam_configuration['ocp-index'] = function('OpamConfOcpIndex')

  function! OpamConfMerlin()
    let l:dir = s:opam_share_dir . "/merlin/vim"
    execute "set rtp+=" . l:dir
  endfunction
  let s:opam_configuration['merlin'] = function('OpamConfMerlin')

  let s:opam_packages = ["ocp-indent", "ocp-index", "merlin"]
  let s:opam_check_cmdline = ["opam list --installed --short --safe --color=never"] + s:opam_packages
  let s:opam_available_tools = split(system(join(s:opam_check_cmdline)))
  for tool in s:opam_packages
    " Respect package order (merlin should be after ocp-index)
    if count(s:opam_available_tools, tool) > 0
      call s:opam_configuration[tool]()
    endif
  endfor
  " ## end of OPAM user-setup addition for vim / base ## keep this line
  let g:opamshare = substitute(system('opam var share'),'\n$','','''')
  execute "set rtp+=" . g:opamshare . "/merlin/vim"
  nnoremap <Leader>t :MerlinTypeOf<CR>
  nnoremap J :MerlinLocate<CR>
endif

set noshowmode

if has("nvim")
  tnoremap <C-\> <C-\><C-n>
  set inccommand=nosplit
endif

let g:black_virtualenv = '/home/cam/neovim3/'

function! FormatBuffer()
  if &filetype ==# 'rust' || &filetype ==# 'ocaml' || &filetype ==# 'haskell'
    if has("nvim")
      execute "silent! Neoformat"
    else
      execute "silent! Autoformat"
    endif
  endif
  if &filetype ==# 'python'
    " execute "Black"
  endif
endfunction

au BufWritePre * call FormatBuffer()

let g:neoformat_enabled_ocaml = ['ocamlformat']
let g:neoformat_haskell_ormolu =
\ { 'exe': 'fourmolu'
\ , 'args': ['--stdin-input-file', '.']
\ , 'stdin': 1
\ }
let g:neoformat_enabled_haskell = ['ormolu']

let g:neoformat_enabled_rust = ['rustfmt']

let g:neoformat_c_clangformat =
\ { 'exe': 'clang-format'
\ , 'args': ['-style=file']
\ , 'stdin': 1
\ }

let g:neoformat_enabled_c = ['clangformat']

function! CornelisLoadWrapper()
  if exists(":CornelisLoad") ==# 2
    CornelisLoad
  endif
endfunction

au BufReadPre *.agda call CornelisLoadWrapper()
au BufWritePost *.agda execute "normal! :CornelisLoad\<CR>"

au BufRead,BufNewFile *.agda call AgdaFiletype()
function! AgdaFiletype()
  let g:cornelis_max_size = 10

  let g:cornelis_split_location = 'Bottom'

  nnoremap <buffer> <leader>l :CornelisLoad<CR>
  nnoremap <buffer> <leader>r :CornelisRefine<CR>
  nnoremap <buffer> <leader>g :CornelisMakeCase<CR>
  nnoremap <buffer> <leader>t :CornelisTypeContext<CR>
  nnoremap <buffer> <leader>T :CornelisTypeContextInfer<CR>
  nnoremap <buffer> <leader>n :CornelisSolve<CR>
  nnoremap <buffer> <leader>a :CornelisAuto<CR>
  nnoremap <buffer> J         :CornelisGoToDefinition<CR>
  nnoremap <buffer> <localleader>k :CornelisPrevGoal<CR>
  nnoremap <buffer> <localleader>j :CornelisNextGoal<CR>

  call cornelis#bind_input("forall", "∀")
  call cornelis#bind_input(":", "∶")
  call cornelis#bind_input("Pi", "ℿ")
  call cornelis#bind_input("mu", "μ")
  call cornelis#bind_input("nu", "ν")
  call cornelis#bind_input("nlambda", "ƛ")
  call cornelis#bind_input("N", "ℕ")
  call cornelis#bind_input("Gamma", "Γ")
  call cornelis#bind_input("tau", "τ")
  call cornelis#bind_input("vdash", "⊢")
  call cornelis#bind_input("equiv", "≡")
  call cornelis#bind_input("nequiv", "≢")
  call cornelis#bind_input("Gamma", "Γ")
  call cornelis#bind_input("tau", "τ")
  call cornelis#bind_input("rho", "ρ")
  call cornelis#bind_input("ell", "ℓ")
  call cornelis#bind_input("Z", "ℤ")
  call cornelis#bind_input("lambda", "λ")
  call cornelis#bind_input("mapsto", "↦")
  call cornelis#bind_input("[]", "☐")
  call cornelis#bind_input("[.]", "⊡")
  call cornelis#bind_input("ltri", "◁")
  call cornelis#bind_input("rtri", "▷")
  call cornelis#bind_input("o/", "∅")
  call cornelis#bind_input("nil", "∅")
  call cornelis#bind_input(">->", "↣")
  call cornelis#bind_input("darrow", "↓")
  call cornelis#bind_input("Darrow", "⇓")
  call cornelis#bind_input("uarrow", "↑")
  call cornelis#bind_input("Uarrow", "⇑")
  call cornelis#bind_input("++", "⧺")
  call cornelis#bind_input("~>", "⇝")
  call cornelis#bind_input("lttri", "⋖")
  call cornelis#bind_input("++" , "⧺")

  call cornelis#unbind_input("len")
endfunction

let g:coqtail_auto_set_proof_diffs = 'on'

luafile ~/.vim/config.lua
luafile ~/.vim/lsp_config.lua
sign define LspDiagnosticsSignError text=X
sign define LspDiagnosticsWarning text=!
sign define LspDiagnosticsSignHint text=?
hi DiagnosticError ctermfg=196  guifg=#ff0000
hi! link DiagnosticUnderlineError SpellBad

set completeopt=menuone,noinsert,noselect
set shortmess+=c

au TextYankPost * silent! lua vim.highlight.on_yank()
