" Allow multiple buffers in the same window
set hidden
" Better command-line completion
set wildmenu

" Ensure that we are in modern vim mode, not backwards-compatible vi mode
set nocompatible
set backspace=indent,eol,start
if has("nvim")
  set guicursor=i:ver25-iCursor
endif

set clipboard=unnamedplus

if has("nvim")
  let g:python3_host_prog = '/home/cam/neovim3/bin/python'
endif

set hidden

filetype off " required for Vundle plugin manager
" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required Plugin 'gmarik/Vundle.vim' vim-c0 plugin on Github repo
Plugin 'cmugpi/vim-c0'

Plugin 'mbbill/undotree'

" NERD tree
"Plugin 'scrooloose/nerdtree'

" Syntastic
"Plugin 'vim-syntastic/syntastic'

" Async syntax checking!
Plugin 'w0rp/ale'

" Whitespace
Plugin 'ntpeters/vim-better-whitespace'

" Language-specific plugins
Plugin 'jez/vim-better-sml'
" This is not the 'official' rust.vim plugin because it doesn't support cargo
" (yet)
"Plugin 'mckinnsb/rust.vim'

Plugin 'neovimhaskell/haskell-vim'
Plugin 'itchyny/vim-haskell-indent'

Plugin 'godlygeek/tabular'
Plugin 'plasticboy/vim-markdown'

" Surround
Plugin 'tpope/vim-surround'

" Let's repeat things!
Plugin 'tpope/vim-repeat'

Plugin 'scrooloose/nerdcommenter'

if has("nvim")
  Plugin 'rbgrouleff/bclose.vim'
endif
Plugin 'francoiscabrol/ranger.vim'

" I enjoy looking good
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
"Plugin 'bling/vim-bufferline'

Plugin 'tpope/vim-fugitive'

" git gutter
Plugin 'airblade/vim-gitgutter'

Plugin 'christophermca/meta5'
Plugin 'flazz/vim-colorschemes'

Plugin 'tpope/vim-obsession'

Plugin 'CharlesGueunet/VimFilify'

if has("nvim")
  Plugin 'sbdchd/neoformat'
else
  Plugin 'Chiel92/vim-autoformat'
endif

Plugin 'psf/black'

Plugin 'junegunn/fzf.vim'

Plugin 'ocaml/vim-ocaml'

Plugin 'autozimu/Languageclient-neovim'

Plugin 'Shougo/deoplete.nvim'

call vundle#end()

" Enable filetype detection and syntax highlighting
syntax on
filetype on
filetype indent on
filetype plugin on

let g:airline#extensions#tabline#enabled = 1

" Helpful information: cursor position in bottom right, line numbers on
" left
set ruler
set number

set tabstop=2
set shiftwidth=2
set expandtab

hi clear SignColumn

if exists('+termguicolors')
  let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
  let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
  set termguicolors
  colorscheme molokai
endif

" Indent as intelligently as vim knows how
set smartindent

" Show multicharacter commands as they are being typed
set showcmd

" Show 80 character limit line
set colorcolumn=80

" Quickly time out on keycodes, but never time out on mappings
set notimeout ttimeout ttimeoutlen=10

let g:bufferline_rotate=1

" buffer stuff
map <C-Right> :bnext<CR>
map <C-Left> :bprevious<CR>
map <C-k> :bnext<CR>
map <C-j> :bprevious<CR>
map <C-W> :bd<CR>

map <C-P> :Files<CR>

"map <C-O> :NERDTree<CR>
"let NERDTreeQuitOnOpen=1
map <C-O> :RangerCurrentDirectory<CR>
nmap <Space> :

nnoremap gV `[v`]

" ARM assembly syntax
let asmsyntax='armasm'
let filetype_inc='armasm'

" Change leader key
let mapleader=","

" gundo tree
nnoremap <F2> :GundoToggle<CR>

" make and associated convenience
nnoremap <leader>m :make<CR>
nnoremap <C-Up> :cn<CR>
nnoremap <C-Down> :cp<CR>

" Search as characters are entered
set incsearch
" Highlight matches
set hlsearch

" Save
nnoremap <leader>w :w<CR>

" Save session
nnoremap <leader>s :mksession<CR>

" Git commit/push
nnoremap <leader>r :! git commit -am "kek" && git push<CR>

" Tab things
nnoremap <Tab> >>
nnoremap <S-Tab> <<

nnoremap <F2> :UndotreeToggle<cr>

let g:haskell_indent_disable=1

" don't clutter with swap files while using gvim
if has("gui_running")
  set noswapfile
  set nobackup
  set nowritebackup
endif

" Enable statusbar
set laststatus=2

set mouse=a

let g:airline_theme='luna'
let g:bufferline_echo=0

let g:ale_sign_error = '>>'
let g:ale_sign_warning = '!!'
let g:ale_set_highlights = 0

let g:airline#extensions#ale#enabled = 1
let g:ale_linters = {
      \  'tex' : [],
      \  'latex' : [],
      \  'ocaml' : ['merlin'],
      \  'bash' : [],
      \  'haskell' : ['stack-build'],
      \  'python' : [ 'pylint' ]
      \}


if &filetype ==# 'ocaml'
" aaaaaaaaaaaaaaa ftplugin isn't working so we have to do this every time
" if neovim stalls on open it's because opam is being terrible

  " ## added by OPAM user-setup for vim / base ## 93ee63e278bdfc07d1139a748ed3fff2 ## you can edit, but keep this line
  let s:opam_share_dir = system("opam config var share")
  let s:opam_share_dir = substitute(s:opam_share_dir, '[\r\n]*$', '', '')

  let s:opam_configuration = {}

  function! OpamConfOcpIndent()
    execute "set rtp^=" . s:opam_share_dir . "/ocp-indent/vim"
  endfunction
  let s:opam_configuration['ocp-indent'] = function('OpamConfOcpIndent')

  function! OpamConfOcpIndex()
    execute "set rtp+=" . s:opam_share_dir . "/ocp-index/vim"
  endfunction
  let s:opam_configuration['ocp-index'] = function('OpamConfOcpIndex')

  function! OpamConfMerlin()
    let l:dir = s:opam_share_dir . "/merlin/vim"
    execute "set rtp+=" . l:dir
  endfunction
  let s:opam_configuration['merlin'] = function('OpamConfMerlin')

  let s:opam_packages = ["ocp-indent", "ocp-index", "merlin"]
  let s:opam_check_cmdline = ["opam list --installed --short --safe --color=never"] + s:opam_packages
  let s:opam_available_tools = split(system(join(s:opam_check_cmdline)))
  for tool in s:opam_packages
    " Respect package order (merlin should be after ocp-index)
    if count(s:opam_available_tools, tool) > 0
      call s:opam_configuration[tool]()
    endif
  endfor
  " ## end of OPAM user-setup addition for vim / base ## keep this line
  let g:opamshare = substitute(system('opam config var share'),'\n$','','''')
  execute "set rtp+=" . g:opamshare . "/merlin/vim"
endif

if &filetype ==# 'ocaml'
  nnoremap <Leader>t :MerlinTypeOf<CR>
endif

set noshowmode

if has("nvim")
  tnoremap <C-\> <C-\><C-n>
endif

augroup vimmic_c_ale_config
  autocmd FileType c let g:ale_c_gcc_executable = Filify#process('.ale_config', {'default_return':'gcc', 'recurse':'true'})
  autocmd FileType h let g:ale_c_gcc_executable = Filify#process('.ale_config', {'default_return':'gcc', 'recurse':'true'})
augroup END

let g:black_virtualenv = '/home/cam/neovim3/'

let g:neoformat_enabled_ocaml = ['ocaml']

function! FormatBuffer()
  if &filetype ==# 'rust' || &filetype ==# 'haskell' || &filetype ==# 'c' || &filetype ==# 'ocaml'
    if has("nvim")
      execute "Neoformat"
    else
      execute "Autoformat"
    endif
  endif
  if &filetype ==# 'python'
    execute "Black"
  endif
endfunction

au BufWritePre * call FormatBuffer()

let g:vim_markdown_folding_disabled = 1

let g:neoformat_enabled_ocaml = ['ocamlformat']
let g:neoformat_enabled_haskell = ['ormolu']

let g:LanguageClient_serverCommands = {
  \ 'rust': ['rust-analyzer']
  \ }

let g:LanguageClient_useVirtualText = "No"

function LC_setup()
  if has_key(g:LanguageClient_serverCommands, &filetype)
    nmap <Leader>t <Plug>(lcn-hover)
    nmap J <Plug>(lcn-definition)

    inoremap <expr> <CR> (pumvisible() ? "\<c-y>" : "\<CR>")

    inoremap <silent><expr> <TAB>
      \ pumvisible() ? "\<C-n>" :
      \ <SID>check_back_space() ? "\<TAB>" :
      \ deoplete#manual_complete()
  endif
endfunction

autocmd FileType * call LC_setup()

let g:deoplete#enable_at_startup = 1

call deoplete#custom#option('auto_complete', 0)

set completeopt-=preview

function! s:check_back_space() abort "{{{
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~ '\s'
endfunction "}}}

