# Cameron "CT075" Wong
#
# My general-purpose zsh runtime config file. For the most part, this file
# handles most of the main logic that moves around between my various machines.
# By exporting specific environment variables in the file "~/.host", each
# machine can very cleanly selectively choose which parts of my overall setup
# are sourced or not.
#
# Draws very heavy inspiration from Jake Zimmerman's dotfiles repository.

# Load configurations for this host
source ~/.host

# This is needed by some of the other setup modules.
export SYSBASE_HOME="$HOME/sys_base"

LOADED=()

load_module() {
  module=$1
  if [ -f "$module" ]; then
    source "$module"

    # Check that all dependencies have been satisfied
    for dep in $MODULE_DEPS; do
      if [[ ${LOADED[(i)$dep]} -le ${#LOADED} ]]; then
        echo "Error: Module $module requires $dep but $dep is not loaded! Skipping."
        return
      fi
    done

    # Actually perform module functions
    # TODO: actually figure out a sane system to have module-level parameters
    module_exec

    # Make sure module loading actually worked
    if [ "$?" != "0" ]; then
      echo "Unable to load module $module. Skipping."
      return
    fi

    # Tell the system that we've loaded it
    LOADED+=MODULE_NAME
    echo "LOADED MODULE $MODULE_NAME"

    # Unset all of the variables set for this system
    unset MODULE_NAME
    unset MODULE_DEPS
    unset -f module_exec
  else
    echo "Unable to find module $module. Oops? Skipping."
  fi
}

# Check whether to use OH-MY-ZSH config
# We do this *first*, before the next step (host-specific scripts) because
# oh-my-zsh could possibly overwrite aliases we want to preserve. It's in
# keeping with the actual recommended usage of oh-my-zsh.
if [[ -n $OHMYZSH ]]; then
  load_module $SYSBASE_HOME/dotfiles/ohmyzsh
fi

# Run host-specific scripts
SYSTEM_SCRIPTS=$SYSBASE_HOME/dotfiles/hosts/$SYSNAME
if ! [[ -d $SYSTEM_SCRIPTS ]]; then
  echo "No hosts folder present for this system. Creating empty folder and sourcing default."
  mkdir $SYSTEM_SCRIPTS
  SYSTEM_SCRIPTS=$SYSBASE_HOME/hosts/default
fi
chmod +x $SYSTEM_SCRIPTS/main.sh
$SYSTEM_SCRIPTS/main.sh

