# Things that get started with the session.

# Start XDG autostart .desktop files using dex. See also
# https://wiki.archlinux.org/index.php/XDG_Autostart
exec dex --autostart --environment i3

# Idle handling. The lock script is ~/.config/sway/lock, a symlink into
# sys_base/scripts/swaylock.
exec swayidle -w timeout 600 '~/.config/sway/lock' before-sleep 'block'

exec systemctl --user import-environment DISPLAY WAYLAND_DISPLAY SWAYSOCK
exec hash dbus-update-activation-environment 2>/dev/null && dbus-update-activation-environment --systemd DISPLAY WAYLAND_DISPLAY SWAYSOCK

# NetworkManager is the most popular way to manage wireless networks on Linux,
# and nm-applet is a desktop environment-independent system tray GUI for it.
exec nm-applet

exec sway-audio-idle-inhibit
