# Dropdown terminal. $title and $term come from 00-variables.conf.

for_window [app_id="$title"] floating enable, move scratchpad, resize set width 500 height 400

exec $term
bindsym $mod+t scratchpad show
