# Window and session management.

# kill focused window
bindsym $mod+Shift+q kill

# reload the configuration file
bindsym $mod+Shift+c reload
# restart sway in place, preserving the layout/session
bindsym $mod+Shift+y restart

bindsym $mod+x exec "~/.config/sway/lock"
bindsym $mod+Shift+x exec "swaynag -t warning -m 'You pressed the exit shortcut. Do you really want to exit sway? This will end your Wayland session.' -B 'Yes, exit sway' 'swaymsg exit'"
