# Launching things.

# start a terminal
bindsym $mod+Shift+Return exec alacritty

# start a program launcher
bindsym $mod+p exec "wofi --show=drun,run"
# A more modern dmenu replacement is rofi:
# bindcode $mod+40 exec "rofi -modi drun,run -show drun"
# There also is i3-dmenu-desktop which only displays applications shipping a
# .desktop file. It is a wrapper around dmenu, so you need that installed.
# bindcode $mod+40 exec i3-dmenu-desktop

# screenshots
bindsym $mod+s exec XDG_CURRENT_DESKTOP=sway flameshot gui --raw | wl-copy
#bindsym $mod+Shift+s exec flameshot gui
bindsym $mod+Shift+s exec grim -g "$(slurp -d)" - | wl-copy -t image/png

mode "startapp" {
        bindsym $mod+c exec "i3-msg mode default; vivaldi --force-dark-mode"
        bindsym $mod+f exec "i3-msg mode default; nautilus"

        bindsym Return mode "default"
        bindsym Escape mode "default"
}

bindsym $mod+Shift+p mode startapp
