# Jumping between monitors. Output geometry lives in 20-output.conf.

#bindsym $mod+w focus output eDP-1
#bindsym $mod+e focus output HDMI-A-1
#bindsym $mod+r focus output HDMI-A-1

#bindsym $mod+Shift+w move workspace to output eDP-1
#bindsym $mod+Shift+e move workspace to output HDMI-A-1
#bindsym $mod+Shift+r move workspace to output HDMI-A-1

bindsym $mod+w focus output DP-2
bindsym $mod+e focus output HDMI-A-1
bindsym $mod+r focus output eDP-1

bindsym $mod+Shift+w move workspace to output DP-2
bindsym $mod+Shift+e move workspace to output HDMI-A-1
bindsym $mod+Shift+r move workspace to output eDP-1
