#!/bin/bash

_pull_update() {
  git pull
  echo $current_epoch > $HOME/.last_updated
}

_push_update() {
  git push
}

current_epoch=$(date +%s)

if [ -e $HOME/.last_updated ]; then
  last_epoch=$(<$HOME/.last_updated)
else
  last_epoch=$current_epoch
  echo $current_epoch > $HOME/.last_updated
fi

pushd &> /dev/null
cd $SYSBASE_HOME

if [ -n "$(git log --branches --not --remotes)" ]; then
  echo "Local changes to sys_base detected. Push to remote?"
  read line
  if [[ "$line" == Y* ]] || [[ "$line" == y* ]] || [ -z "$line" ]; then
    _push_update
  else
    popd &> /dev/null
    [ $PS1 ] && return || exit;
  fi
fi

popd &> /dev/null

