#!/bin/bash

_pull_update() {
  git pull
  echo $current_epoch > $HOME/.last_updated
}

_push_update() {
  git add -A
  echo "Commit message:"
  read msg
  git commit -m "$msg"
  git push
}

current_epoch=$(date +%s)

if [ -e $HOME/.last_updated ]; then
  last_epoch=$(<$HOME/.last_updated)
else
  last_epoch=$current_epoch
  echo $current_epoch > $HOME/.last_updated
fi

pushd &> /dev/null
cd $SYSBASE_HOME

git diff --exit-code &> /dev/null
if [ $? -ne 0 ]; then
  echo "Local changes to sys_base detected. Commit to remote?"
  read line
  if [[ "$line" == Y* ]] || [[ "$line" == y* ]] || [ -z "$line" ]; then
    _push_update
  else
    popd &> /dev/null
    [ $PS1 ] && return || exit;
  fi
fi

# check for updates at most once per week
epoch_diff=$(($current_epoch-$last_epoch))
if [ $epoch_diff -gt 7 ]; then
  _pull_update
fi

popd &> /dev/null

